name: build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [ '3.9' ]

    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      # step 1: install dependencies
      - run: pip install nox
      - run: pip install types-requests
      # step 2: run test
      - run: nox --non-interactive --session "tests-${{ matrix.python }}"
      #- run: nox --non-interactive --session "lint"
